# Generated by Django 4.2.7 on 2025-02-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_geolocation_city_alter_geolocation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
