# Generated by Django 4.2.7 on 2025-02-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_geolocation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='timezone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
