version: '3'

services:
  db_postgis:
    container_name: db_postgis
    image: postgis/postgis:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web_gc:
    container_name: web_gc
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py shell < create_superuser.py && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db_postgis
    restart: "on-failure"

volumes:
  postgres_data:
