name: Run Tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Docker (Docker jest już preinstalowany na Ubuntu)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Budowanie obrazu Docker
      - name: Build Docker image
        run: |
          docker build -t geolocation_capture:${{ github.sha }} geolocation_capture .

      # Uruchamianie testów w kontenerze
      - name: Run tests
        run: |
          docker run --rm geolocation_capture:${{ github.sha }} pytest geolocation_capture/management/tests.py
