name: Run Tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker Compose 
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Run Docker Compose + test
      - name: Build and run tests with Docker Compose
        run: |
          docker-compose -f geolocation_capture/docker-compose.yml up -d --build
          docker-compose exec -T web_gc python manage.py test
          docker-compose down
