name: Run Tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker build
      - name: Build Docker image
        run: |
          docker build -t geolocation_capture:${{ github.sha }} -f geolocation_capture/Dockerfile geolocation_capture

      # Run test in container
      - name: Run tests
        run: |
          docker run --rm geolocation_capture:${{ github.sha }} pytest geolocation_capture/management/tests.py
